on: [pull_request]

jobs:
  frontend_test:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the app
      run: npm install && npm run build
      working-directory: ./frontend  
    
    - name : Run the linting subscription
      run: npm run lint
      working-directory: ./frontend

  backend_test:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    - name: Build le dotnet
      run: dotnet build --configuration Release
        
    - name: Publish the app
      run: dotnet publish -c Release --property:PublishDir=publish # Publish the app to the API project publish folder
      working-directory: ./backend # Specify where to find the solution file in repository
