on:
  release:
    types: [published]
 
permissions:
  id-token: write

env: 
  AZURE_RG_NAME: rg-${{ vars.PROJECT_NAME }}-${{ vars.AZURE_RESOURCE_IDENTIFIER }}

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the app
      run: npm install && npm run build
      working-directory: ./frontend  
    
    - name : Run the linting subscription
      run: npm run lint
      working-directory: ./frontend

    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v4
      working-directory: ./frontend
      with:
        name: frontend-artifacts
        path: |
          dist
          !dist/**/*.md

  backend_ci:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    - name: Build le dotnet
      run: dotnet build --configuration Release
      working-directory: ./backend
      
    - name: Publish the app
      run: dotnet publish -c Release --property:PublishDir=publish # Publish the app to the API project publish folder
      working-directory: ./backend # Specify where to find the solution file in repository

    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      working-directory: ./backend
      with:
        name: backend-artifacts
        path: |
          publish
          !publish/**/*.md

  frontend_cd:
    runs-on: ubuntu-latest
    environment: production
    needs: [frontend_ci,backend_ci]

  backend_cd:
    runs-on: ubuntu-latest
    environment: production
    needs: [frontend_ci,backend_ci]
